project:
  type: website

website:
  title: "Iraq Logistics Simulator"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Simulation"
        href: simulate.html
format:
  html:
    theme: cosmo
    css: assets/style.css
